### ISSUE TITLE
How Can I get A Pro License

### ISSUE THREAD

**Issue by lincolnred8** [huacnlee/bluedoc#143]
Hi @huacnlee , I want to put this product into our live site , so I want to check how can I get a valid pro license.

If I remove your project Name 'bluedoc', the pro license is enough?

Kindly .

**Comment by Eric-Guo** [comment]
https://bluedoc.org/en/pricing/

I'm only user, but I think you can check above URL.

**Comment by huacnlee** [comment]
https://github.com/huacnlee/bluedoc/pull/144
